export enum postTypes {
  FETCH_POST_REQUEST = "FETCH_POST_REQUEST",
  FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE = "FETCH_POST_FAILURE",
  FILTER_POST_REQUEST = "FILTER_POST_REQUEST",
  FILTER_POST_SUCCESS = "FILTER_POST_SUCCESS",
  FILTER_POST_FAILURE = "FILTER_POST_FAILURE"
}
